[2주차] 박효진 미션 제출합니다.
CEOS-Developers/react-todo pull request #2
Opened 2019-10-05 13:15 UTC by gywls517

미리 단위를 분리하고 구현을 시작했는데, component 하나를 완벽하게 끝내고 다른 component 구현을 시작하는 게 아니라 번갈아가면서 하느라 component 별 commit을 제대로 작성하지 못했어요. 앞으로 component 단위 별로 코드를 작성하고 끝낼 때마다 commit하는 연습을 해야 할 것 같아요!
그리고 to-do-list 사이의 간격을 styled-component의 display:flex; flex-direction:column, justify-content:space-between;으로 띄워보려 했는데 잘 안 되어서 일단 list 사이에 margin을 두어 간격을 띄웠어요. 왜 안 되는지 내일 같이 얘기해보면 좋을 것 같아요!

2019-10-05 14:13 UTC, MrKwon requested changes
안녕하세요. 효진님. 리뷰어 민철입니다 🤠
처음으로 리뷰를 남겨요.
전체적으로 구현 잘 해주셨습니다.
몇 가지 추가적으로 학습하시면 좋을 것 같은 부분에 대해 코멘트를 남겨드렸어요.
참고하셔서 학습하는데 도움이 될 수 있으면 좋을 것 같아요.
현재 미션을 진행하고 있는 효진님의 브랜치에서 피드백을 반영하면서 커밋을 더 쌓고 이 페이지의 링크와 함께 슬랙 메시지로 저를 태그 해주세요 ! ( 이 PR 을 close 하지 않으셔도 자동으로 commit 이 쌓여요 ! )
화이팅 !

2019-10-05 14:13 UTC, MrKwon commented on src/components/todo/Todo.js
> +            if(content==''){ //아무 것도 입력하지 않았을 때
javascript 에서 ``==`` 연산자와 ``===`` 연산자는 의미가 달라요.
전자는 Abstract하게 Equality 를 비교하는 용도로 사용하고 후자는 Strict 하게 Equality 를 비교하는 용도로 사용해요.
추가 자료 [링크](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Equality_comparisons_and_sameness) 참고해서 조금 더 학습해보는 것이 좋을 것 같네요 😁

2019-10-05 14:13 UTC, MrKwon commented on src/components/todo/Todo.js
> +        <TodoInput onSubmit={
onSubmit 안의 동작을 함수로 분리 해보는 것은 어떨까요 ?

ZeroCho 님의 블로그에 [컴포넌트 이벤트 연결(바인딩)](https://www.zerocho.com/category/React/post/578232e7a479306028f43393) 이라는 글을 참고해서 도전해보는 것도 좋을 것 같아요.

추가적으로 **this binding** 에 대하여 학습해봐도 좋을 것 같네요. 구글에 **this binding** 을 검색하면 많은 자료들이 나와요.

그리고 이 **this binding** 왜 해줘야 하는지, javascript 진영에서는 이 귀찮은 문제를 어떻게 해결하고 있는지도 학습하면 더 좋을 것 같아요 🤠

2019-10-05 14:13 UTC, MrKwon commented on src/components/todo/Todo.js
> +        }></TodoInput>
비어있는 태그는 Self Closing 을 하면 어떨까요?

2019-10-05 14:13 UTC, MrKwon commented on src/components/todo/Todo.js
> +import {TodoCard} from './TodoCard.js';
import 에 사용하는 중괄호 안의 공백이 일정하지 않은 모습을 발견할 수 있어요.
어떤 부분은
```
import { Component } from 'package';
```
어떤 부분은
```
import {Component} from 'package';
```
네요.

별 다른 이유가 없다면 동일한 스타일을 유지하도록 하는 것이 좋지 않을까요? 😂

2019-10-05 14:13 UTC, MrKwon commented on src/components/todo/TodoCard.js
> +    let liList = [];
``liList`` 라는 이름보다 이 배열의 용도를 명확하게 나타낼 수 있는 이름은 없을까요?

2019-10-05 14:13 UTC, MrKwon commented on src/components/todo/TodoCard.js
> +    if(liList.length>0){result=liList}; //배열에 값이 들어왔을 때에 그것을 출력하도록
코드들이 한글자 한글자 너무 사이가 좋아서 답답해 보여요 😂
```
if (condition) {
   // logic
}
```

로 바꿔보는 것은 어떨까요?

그리고 if 문 뒤의 세미콜론(``;``) 을 발견했어요 !

2019-10-05 14:13 UTC, MrKwon commented on src/components/todo/TodoInput.js
> +          <AddButton type="submit" value="ADD"></AddButton>
Self Closing 권장

2019-10-05 19:06 UTC, greatSumini requested changes
안녕하세요 리뷰어 최수민입니다 😹 
이번 제출물을 보니, 이제는 정말 어엿한 리액트인이 되신 것 같아 매우 뿌듯합니다.
조금 더 고민해보시면 좋을만한 부분들 리뷰해드렸으니 참고해주세요!
피드백 반영 후 커밋해주시면 머지해드리겠습니닿
+) space-between시에 children component들 사이의 space는 어떻게 결정될까요? 이것에 대해서 고민해보시면 답을 찾으실 수 있을 것 같습니다!

2019-10-05 19:06 UTC, greatSumini commented on README.md
> +              배열에 값 없을 때 표시할 값이 없다는 것 알리기
정리 깔끔하네요 좋습니다 👍

2019-10-05 19:06 UTC, greatSumini commented on src/App.js
> +import {Todo} from './components/todo/Todo.js';
모든 import, export를 Named 방식으로 바꾸셨는데, 특별한 이유가 있으신가요??

2019-10-05 19:06 UTC, greatSumini commented on src/components/todo/Todo.js
> +          function (content) {
Udemy 강의에서 언급된 arrow function을 사용해보셔도 좋을 것 같아요!
[참고할만한 글](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Functions/%EC%95%A0%EB%A1%9C%EC%9A%B0_%ED%8E%91%EC%85%98)

2019-10-05 19:06 UTC, greatSumini commented on src/components/todo/Todo.js
> +            let list = [...this.state.todoList]; //기본 배열과 값이 같은 새 배열 생성
list가 아닌, 변수의 용도를 더 명확히 알 수 있는 네이밍이면 좋을 것 같아요!
+) Spread operator 너무 잘 써주셔서 상당히 기쁩니다

2019-10-05 19:06 UTC, greatSumini commented on src/components/todo/TodoCard.js
> +    for (let i in list) {
while문도, for문도 아닌 for in문을 선택해주신 점이 정말 인상적이네요. 좋습니다 👍 
하지만 map함수를 쓰시면 훨씬 깔끔하게 구현할 수 있어요! [참고할만한 글](https://www.zerocho.com/category/JavaScript/post/5acafb05f24445001b8d796d)

2019-10-05 19:06 UTC, greatSumini commented on src/components/todo/TodoCard.js
> +      liList.push(<List key={i} onClick={function (e) { //onClick 이벤트 발생했을 때 클릭한 내용 삭제되도록
arrow function 사용하면 좋을 것 같아요2

2019-10-05 19:06 UTC, greatSumini commented on src/components/todo/TodoCard.js
> +        this.props.onClicked(i); // props의 onClicked를 핸들러에 넣어줌.
prop으로 function을 넘기는 개념에 대해 잘 이해하신 것 같아 좋네요 😄

2019-10-05 19:06 UTC, greatSumini commented on src/components/todo/TodoInput.js
> +    padding:50px;
px사용은 최대한 자제해주세요!

2019-10-05 19:06 UTC, greatSumini commented on src/components/todo/TodoInput.js
> +const AddButton = styled.input`
InputWrapper와 AddButton 네이밍 너무 좋습니다 👍

2019-10-05 19:06 UTC, greatSumini commented on src/components/todo/TodoInput.js
> +const InputWrapper = styled.div`
```suggestion
const InputWrapper = styled.form`
```
위의 변경점을 반영했을 때의 장점과 단점에 대해서 생각해보세요~ 🤔

2019-10-05 19:06 UTC, orange-mush commented on src/components/todo/TodoInput.js
> +          onSubmit={function (e) {
arrow function 사용하면 좋을 것 같아요3

2019-10-05 19:06 UTC, orange-mush commented on src/components/todo/TodoInput.js
> +          <input type="text" name="content" placeholder="TODO를 입력하세요."></input>
```suggestion
          <input type="text" value={this.state.content} placeholder="TODO를 입력하세요."></input>
```
변화하는 값에 대해서 최대한 state를 활용해주시면 확장성이 매우 좋아집니다!
예를 들어, 입력값이 10글자 이하인 경우 입력창 밑에 '10글자 이상 입력해주세요'라는 글씨를 띄우고 싶은 상황에서 유용하게 쓸 수 있죠.

2019-10-05 19:32 UTC, greatSumini reviewed
보다보니 더 보여서 추기합니다 🙈

2019-10-05 19:32 UTC, orange-mush commented on src/components/todo/Todo.js
> +const Card = styled.div`
Card 보다 의도와 역할을 명확히 드러내는 이름이 있을 것 같아요
ex) Wrapper, Container, Block, ...

2019-10-05 19:32 UTC, orange-mush commented on src/components/todo/Todo.js
> +              todoList: list
```suggestion
              todoList: [...this.state.todoList.slice(0, index), ...this.state.todoList.slice(index + 1, this.state.todoList.length)]
```
라고 바꿀 수 있습니다.
```suggestion
              todoList: [todoList.slice(0, index), ...todoList.slice(index + 1, todoList.length)]
```
위에서 const { todoList } = this.state; 라고 선언해줬다면 이렇게 훨씬 깔끔해지구요!
이를 destructure assignment라고 합니다. [참고할만한 글](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment)에서 객체 구조 분해 부분을 보시면 이해되실거에요!

2019-10-05 19:32 UTC, orange-mush commented on src/components/todo/TodoCard.js
> +    let result=<div>표시할 TODO가 없어요!</div>; //처음에 뜨도록
고민해주신 흔적이 보이네요 ㅎㅎ 이를 좀 더 세련되게 해결할 수 있는 '조건부 렌더링' 이라는 방법이 있습니다.
[참고](https://reactjs-kr.firebaseapp.com/docs/conditional-rendering.html)해주세요!
(대부분의 경우의 조건부 렌더링에서 '논리 && 연산자가 있는 인라인 조건' 방식이 선호됩니다.)

2019-10-05 19:32 UTC, orange-mush commented on src/components/todo/TodoCard.js
> +      <ListWrapper>
TodoCard(단수)라는 이름의 Component에 List가 통째로 들어가있는 점이 살짝 어색한 것 같아요! 😂

2019-10-05 23:04 UTC, gywls517 commented on src/App.js
> +import {Todo} from './components/todo/Todo.js';
이번 Udemy 강의에서 처음 알게 된 지식이라 한 번 사용해봤습니다!

2019-10-06 11:29 UTC, greatSumini reviewed
고생하셨습니다 리뷰 반영 후 커밋해주시면 머지해드리겠습니다~

2019-10-06 11:29 UTC, orange-mush commented on src/components/todo/TodoCard.js
> +    let result = <div>표시할 TODO가 없어요!</div>; //처음에 뜨도록
이 부분의 로직 오늘 배운 대로 (조건부렌더링) 수정해봐도 좋을 것 같아요!
[참고할만한 글](https://reactjs-kr.firebaseapp.com/docs/conditional-rendering.html)에서 논리 && 연산자가 있는 인라인 조건 참고하면됩니다~

2019-10-06 11:29 UTC, orange-mush commented on src/App.js
> +import { Intro } from './components/Intro.js';
각 Component는 default로 export 하는게 '**옳은**' 방향이라고 생각해도 될 것 같아용

2019-10-06 12:21 UTC, greatSumini approved these changes

2019-10-06 12:22 UTC, merged